domains:
- domain: beta.pennyvault.com
  type: PRIMARY
name: pv-frontend-beta
region: sfo
static_sites:
- environment_slug: html
  github:
    branch: beta
    deploy_on_push: true
    repo: penny-vault/frontend
  name: pv-frontend-beta
  routes:
  - path: /
  source_dir: /
  catchall_document: index.html